* NOTE: This file includes content generated by generative AI (Windsurf AI Autocomplete, Windsurf Command). *



-- Create

CREATE TABLE IF NOT EXISTS NOMNOM (
NAME TEXT NOT NULL,
NEIGHBORHOOD TEXT NOT NULL,
CUISINE TEXT NOT NULL,
REVIEW REAL NOT NULL,
PRICE TEXT,
HEALTH TEXT
);


-- Insert

INSERT INTO NOMNOM (NAME, NEIGHBORHOOD, CUISINE, REVIEW, PRICE, HEALTH) VALUES
('Pasta Palace', 'Downtown', 'Italian', 4.5, '$$', NULL),
('Sushi Central', 'Uptown', 'Japanese', 4.7, '$$$', 'B'),
('Taco Town', 'Midtown', 'Mexican', 4.2, '$', 'B'),
('Curry Corner', 'Downtown', 'Indian', 4.3, '$$', 'A'),
('Burger Barn', 'Suburbs', 'American', 4.0, '$', NULL),
('Pizza Palace', 'Midtown', 'Italian', 4.6, '$$$', 'B'),
('Sushi Station', 'Uptown', 'Japanese', 4.8, '$$$', 'A'),
('Curry House', 'Downtown', 'Indian', 4.1, '$$', NULL),
('Taco Terrace', 'Suburbs', 'Mexican', 4.4, '$', 'A'),
('Burger Bistro', 'Country', 'American', 4.3, '$$', 'C');


-- Select

SELECT *
FROM NOMNOM;

SELECT *
FROM NOMNOM
WHERE CUISINE = 'Japanese'
ORDER BY REVIEW DESC;

SELECT *
FROM NOMNOM
WHERE REVIEW >= 4.5;

SELECT *
FROM NOMNOM
WHERE NAME LIKE '%Burger%';

SELECT *
FROM NOMNOM
ORDER BY PRICE ASC, REVIEW DESC
LIMIT 5;

SELECT COUNT(*) AS 'Total Restaurants'
FROM NOMNOM;

SELECT AVG(REVIEW) AS 'Average Review'
FROM NOMNOM;

SELECT MIN(REVIEW) AS 'Lowest Review', MAX(REVIEW) AS 'Highest Review'
FROM NOMNOM;

SELECT SUM(LENGTH(PRICE)) AS 'Total Price'
FROM NOMNOM;

SELECT NAME AS 'No Health Rating', REVIEW AS 'Rating' FROM NOMNOM
WHERE HEALTH IS NULL
ORDER BY REVIEW DESC;


-- Alter

ALTER TABLE NOMNOM
ADD COLUMN DELIVERY
BOOLEAN DEFAULT FALSE;

UPDATE NOMNOM SET DELIVERY = TRUE
WHERE NAME IN ('Pasta Palace', 'Sushi Central', 'Taco Town');


-- Select after Alter

SELECT *
FROM NOMNOM;


-- Backup

CREATE TABLE IF NOT EXISTS NOMNOM_BACKUP AS
SELECT * FROM NOMNOM;


-- Delete

DELETE FROM NOMNOM;

SELECT *
FROM NOMNOM;


-- Drop

DROP TABLE IF EXISTS NOMNOM;


SELECT * FROM NOMNOM_BACKUP;