-- * NOTE: This file includes content generated by generative AI (Windsurf AI Autocomplete, Windsurf Command). *

--

-- Create

CREATE TABLE IF NOT EXISTS EMPLOYEES (
EMPLOYEE_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NAME NOT NULL,
EMAIL TEXT UNIQUE NOT NULL,
HIRE_DATE TEXT NOT NULL,
JOB_ID TEXT NOT NULL,
SALARY REAL NOT NULL
);


-- Insert

INSERT INTO EMPLOYEES (NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY) VALUES
('John Doe', 'john@example.com', '2020-01-01', 'CEO', 10000.0),
('Jane Doe', 'jane@example.com', '2020-01-02', 'CTO', 8000.0),
('Bob Smith', 'bob@example.com', '2020-01-03', 'DEV', 6000.0),
('Alice Johnson', 'alice@example.com', '2020-01-04', 'DEV', 6000.0),
('David Lee', 'david@example.com', '2020-01-05', 'DEV', 6000.0);


-- Select

SELECT
*
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID;

SELECT
COUNT(JOB_ID) AS 'Ppl. In Job',
JOB_ID AS 'Job (ID)'
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT
NAME AS 'Name',
JOB_ID as 'Job (ID)',
SALARY AS 'Salary',
HIRE_DATE AS 'Hired'
FROM EMPLOYEES
WHERE JOB_ID = 'DEV'
ORDER BY HIRE_DATE DESC;
