-- * NOTE: This file includes content generated by generative AI (Windsurf AI Autocomplete, Windsurf Command). *


-- Create

CREATE TABLE IF NOT EXISTS CUSTOMERS (
CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NAME TEXT NOT NULL,
EMAIL TEXT UNIQUE NOT NULL,
PHONE TEXT NOT NULL,
ADDRESS TEXT NOT NULL,
CITY TEXT NOT NULL,
STATE TEXT NOT NULL,
ZIP_CODE TEXT NOT NULL,
COUNTRY TEXT NOT NULL,
PRODUCT TEXT NOT NULL
);


-- Insert

INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY, PRODUCT) VALUES
('John Doe', 'john@example.com', '123-456-7890', '123 Main St', 'Anytown', 'CA', '12345', 'USA', 'Laptop'),
('Jane Smith', 'jane@example.com', '987-654-3210', '456 Elm St', 'Othertown', 'ON', '67890', 'Canada', 'Smartphone'),
('Bob Johnson', 'bob@example.com', '555-555-5555', '789 Oak St', 'Thirdtown', 'TX', '24680', 'USA', 'Tablet'),
('Alice Johnson', 'alice@example.com', '111-111-1111', '101 Pine St', 'Fourthtown', 'FL', '13579', 'USA', 'Monitor'),
('David Lee', 'david@example.com', '222-222-2222', '202 Maple St', 'Fifthtown', 'BC', '24680', 'Canada', 'Printer'),
('Emily Wilson', 'emily@example.com', '333-333-3333', '303 Oak St', 'Sixthtown', 'Bavaria', '12345', 'Germany', 'Desktop'),
('Matthew Brown', 'matthew@example.com', '444-444-4444', '404 Elm St', 'Seventhtown', 'Attica', '12345', 'Greece', 'Router'),
('Sarah Davis', 'sarah@example.com', '555-555-5555', '505 Maple St', 'Eighthtown', 'Honshu', '12345', 'Japan', 'Camera'),
('Alexander Dorsey', 'alexander@example.com', '666-666-6666', '606 Pine St', 'Ninethtown', 'Andalusia', '12345', 'Spain', 'Gaming Console');


-- Select

SELECT * FROM CUSTOMERS;

SELECT NAME AS 'Names that start with "a" and contain "or"'
FROM CUSTOMERS
WHERE LOWER(NAME) LIKE 'a%' AND LOWER(NAME) LIKE '%or%';

SELECT NAME, ADDRESS, CITY, STATE, COUNTRY, PRODUCT
FROM CUSTOMERS;

SELECT PRODUCT, COUNT(PRODUCT)
FROM CUSTOMERS
GROUP BY PRODUCT;

SELECT COUNTRY AS, COUNT(PRODUCT)
FROM CUSTOMERS
GROUP BY COUNTRY;